# This file contains the information needed to deploy your app to the Shopify platform.
# For the complete manifest specification, see: https://shopify.dev/docs/apps/tools/cli/app-configuration

name = "Warranty Activation Form"
client_id = "YOUR_CLIENT_ID" # Replace with your Shopify Partner API key
application_url = "YOUR_APPLICATION_URL" # Replace with your app's URL
embedded = true

[access_scopes]
# Define the scopes your app needs
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "YOUR_REDIRECT_URL" # Replace with your redirect URL
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false